name: Phase 2 - CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        run: |
          docker build -t pankaj5832/django-backend:latest ./backend
          docker push pankaj5832/django-backend:latest

      - name: Build & Push Frontend
        run: |
          docker build -t pankaj5832/react-frontend:latest ./frontend
          docker push pankaj5832/react-frontend:latest


  deploy-self-hosted:
    name: Deploy (Self-hosted Runner)
    needs: build-and-push
    runs-on: self-hosted
    if: ${{ vars.DEPLOY_TARGET == 'local' }}

    steps:
      - uses: actions/checkout@v4

      - name: Deploy using Docker Compose
        run: |
          docker compose -f docker-compose.prod.yml down
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d


  deploy-aws:
    name: Deploy (AWS EC2)
    needs: build-and-push
    runs-on: ubuntu-latest
    if: ${{ vars.DEPLOY_TARGET == 'aws' }}

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd app
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
